language: python
os: linux
sudo: false
 
env:
  global:
    - DISPLAY=:99.0

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
      before_install:
        - mkdir gtabview/numpy && echo 'raise ImportError()' > gtabview/numpy/__init__.py
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
            - python-xlrd
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
            - python-matplotlib
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
      before_install:
        - pip install -q pandas
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
            - python-matplotlib
      before_install:
        - pip install -q pandas
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
      before_install:
        - mkdir gtabview/numpy && echo 'raise ImportError()' > gtabview/numpy/__init__.py
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
            - python3-xlrd
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
            - python3-matplotlib
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
      before_install:
        - pip install -q pandas
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
            - python3-matplotlib
      before_install:
        - pip install -q pandas

install:
  - pip install coveralls
  - python setup.py -q install

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - nosetests -v --with-coverage --cover-package gtabview tests

after_success:
  - coveralls
