language: python
os: linux
sudo: false
 
env:
  global:
    - DISPLAY=:99.0
    - PIP_DISABLE_PIP_VERSION_CHECK=1
  matrix:
    - TRAVIS_4681_WORKAROUND=1

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  exclude:
    - env: TRAVIS_4681_WORKAROUND=1
  include:
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
      before_install:
        - pip uninstall -qy numpy
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
      before_install:
        - pip install -q xlrd
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
            - python-matplotlib
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
      before_install:
        - pip install -q pandas
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
            - python-matplotlib
      before_install:
        - pip install -q pandas
    - python: 2.7_with_system_site_packages
      addons:
        apt:
          packages:
            - python-qt4
      before_install:
        - pip install -q blaze
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
      before_install:
        - pip uninstall -qy numpy
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
      before_install:
        - pip install -q xlrd
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
      before_install:
        - pip install -q matplotlib
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
      before_install:
        - pip install -q pandas
    - python: 3.2_with_system_site_packages
      addons:
        apt:
          packages:
            - python3-pyqt4
      before_install:
        - pip install -q pandas matplotlib

install:
  - if [ "$TRAVIS_PYTHON_VERSION" = '3.2_with_system_site_packages' ]; then pip install -q 'coverage<4'; fi
  - pip install -q coveralls
  - python setup.py install

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - nosetests -v --with-coverage --cover-package gtabview

after_success:
  - coveralls
