language: python
os: linux
sudo: required
 
env:
  global:
    - DISPLAY=:99.0

matrix:
  include:
    - python: 2.7_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python-qt4
        - sudo apt-get purge -q python-numpy
    - python: 2.7_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python-qt4 python-xlrd
    - python: 2.7_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python-qt4 python-matplotlib
    - python: 2.7_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python-qt4 python-pandas
    - python: 2.7_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python-qt4 python-matplotlib python-pandas
    - python: 3.2_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python3-pyqt4
    - python: 3.2_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python3-pyqt4 python3-xlrd
    - python: 3.2_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python3-pyqt4 python3-matplotlib
    - python: 3.2_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python3-pyqt4 python3-pandas
    - python: 3.2_with_system_site_packages
      before_install:
        - sudo apt-get update -q
        - sudo apt-get install -q python3-pyqt4 python3-matplolib python3-pandas

install:
  - pip install -q coveralls
  - python setup.py -q install

before_script:
  - sh -e /etc/init.d/xvfb start

script:
  - nosetests -v --with-coverage --cover-package gtabview

after_success:
  - coveralls
