name: Test cli installation

on: [push]

jobs:
  test:
    name: test install
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3
          activate-environment: test
      - name: Install dependencies
        run: |
          conda install setuptools
      - name: Run install
        run: |
          python setup.py install
      - name: Run gtabview
        run: |
          gtabview -h
