name: Test on different Python versions

on: [push]

jobs:
  test:
    name: test python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.9", "3.8", "3.7", "2.7"]
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test
      - name: Install dependencies
        run: |
          conda install setuptools pyqt nose pandas numpy xlrd
      - name: Silence fontconfig
        run: |
          fc-cache
      - name: Run tests
        env:
          XDG_RUNTIME_DIR: ${{ runner.temp }}
        run: |
          xvfb-run --auto-servernum nosetests -v
